export const NAMES = [
  { title: "Alexis Martinez" },
  { title: "Matthew Grant" },
  { title: "Amanda Tyler" },
  { title: "Jennifer Reese" },
  { title: "Samantha Smith" },
  { title: "Shannon Flynn" },
  { title: "Paula Smith" },
  { title: "Andrew Mccoy" },
  { title: "Brittany Brown" },
  { title: "Shelly Lee" },
  { title: "Sarah Francis" },
  { title: "John Lawson" },
  { title: "Jessica Buckley" },
  { title: "Don Schneider" },
  { title: "Jeffrey Sullivan" },
  { title: "Cameron Beasley" },
  { title: "Derek Hill" },
  { title: "Roger Patel" },
  { title: "Heather Davis" },
  { title: "Sara Coleman" },
  { title: "Maurice Collier" },
  { title: "Karen Johnson" },
  { title: "Valerie Johnson" },
  { title: "Jay Mosley" },
  { title: "Joan Simmons" },
  { title: "Ellen Young" },
  { title: "Natalie Banks" },
  { title: "Douglas Gomez" },
  { title: "Jessica Brown" },
  { title: "Gregory Schwartz" },
  { title: "Dawn Johnson" },
  { title: "Susan Brown" },
  { title: "Christopher Fuller" },
  { title: "Troy Jones" },
  { title: "Miguel Sanchez" },
  { title: "Elizabeth Davis" },
  { title: "Antonio Mullins" },
  { title: "Geoffrey Rodgers" },
  { title: "Gloria White" },
  { title: "Victoria Gonzales" },
  { title: "Laura Guzman" },
  { title: "Alyssa Powell" },
  { title: "Michael Smith" },
  { title: "Melissa Roth" },
  { title: "Elizabeth Bass" },
  { title: "Gregory Walker" },
  { title: "Micheal Lawson" },
  { title: "Christine White" },
  { title: "Dana Miller" },
  { title: "Kimberly Richardson" },
  { title: "Kathryn Smith" },
  { title: "Richard Brennan" },
  { title: "Eric Bennett" },
  { title: "Lisa Dodson" },
  { title: "Bethany Snyder" },
  { title: "David Johnson" },
  { title: "Daniel Kelly" },
  { title: "Melissa Rivera" },
  { title: "Todd Larson" },
  { title: "Amber Vaughan" },
  { title: "Susan Johnson" },
  { title: "Tammy Scott" },
  { title: "Jason Brown" },
  { title: "James Perez" },
  { title: "Matthew Greene" },
  { title: "Sharon Ramos" },
  { title: "John Smith" },
  { title: "James Davis" },
  { title: "Matthew Lester" },
  { title: "Michael Gonzalez" },
  { title: "Deborah Murray" },
  { title: "Kirk Hall" },
  { title: "Daniel Johnson" },
  { title: "Kimberly Jordan" },
  { title: "Christina Lee" },
  { title: "Tara Ryan" },
  { title: "Kayla Phelps" },
  { title: "Phillip Thompson" },
  { title: "Jeffrey Floyd" },
  { title: "Heather Francis" },
  { title: "Justin Bullock" },
  { title: "David Estrada" },
  { title: "Erica Johnson" },
  { title: "Roberta Erickson" },
  { title: "Philip Nichols" },
  { title: "Cheryl Hurst" },
  { title: "Mindy Woods" },
  { title: "Ryan Ramirez" },
  { title: "Dennis Bates" },
  { title: "Susan Burke" },
  { title: "Mark Lee" },
  { title: "Alicia Rodriguez" },
  { title: "Angela Beltran" },
  { title: "Jodi Lamb" },
  { title: "Johnny Rush" },
  { title: "Darlene Riley" },
  { title: "Diana Gonzalez" },
  { title: "Brittany Munoz" },
  { title: "Timothy Trevino" },
];

export const DEALERS = [
  {
    name: "Joseph Roberts",
    address: "Scotland Minnesota",
    phoneNumber: "052-196-2513x710",
    email: "christopherreynolds@example.com",
    outstandingAmount: 263,
  },
  {
    name: "Gloria Gilbert",
    address: "New Hampshire Colorado",
    phoneNumber: "001-059-167-6718x6255",
    email: "davisjames@example.net",
    outstandingAmount: 3142,
  },
  {
    name: "Julia Santiago",
    address: "Virginia Arkansas",
    phoneNumber: "001-057-108-7154",
    email: "bettytorres@example.net",
    outstandingAmount: 96998,
  },
  {
    name: "Ronald Ewing",
    address: "Alabama Iowa",
    phoneNumber: "001-532-363-8519x9224",
    email: "rebeccaingram@example.net",
    outstandingAmount: 84815,
  },
  {
    name: "Phillip Molina",
    address: "Pennsylvania Utah",
    phoneNumber: "4568837810",
    email: "james16@example.com",
    outstandingAmount: 61512,
  },
  {
    name: "Jose Newton",
    address: "New Brunswick Oregon",
    phoneNumber: "(289)396-9484x84402",
    email: "bianca05@example.net",
    outstandingAmount: 8101,
  },
  {
    name: "Alex Kelly",
    address: "New York South Dakota",
    phoneNumber: "+1-382-822-1780",
    email: "lewissteven@example.com",
    outstandingAmount: 16158,
  },
  {
    name: "Christine Hicks",
    address: "Louisiana New Mexico",
    phoneNumber: "415.507.7837x120",
    email: "keyjerome@example.com",
    outstandingAmount: 38201,
  },
  {
    name: "Laurie Ruiz",
    address: "Newfoundland and Labrador Scotland",
    phoneNumber: "001-140-454-9388x71486",
    email: "cbeck@example.net",
    outstandingAmount: 607,
  },
  {
    name: "James Morris",
    address: "Vermont Northwest Territories",
    phoneNumber: "042.460.6141x43754",
    email: "jakesavage@example.net",
    outstandingAmount: 799,
  },
  {
    name: "Austin Lee",
    address: "Iowa New Mexico",
    phoneNumber: "(742)652-8610x5342",
    email: "upitts@example.net",
    outstandingAmount: 31354,
  },
  {
    name: "David Rush",
    address: "Nebraska Kentucky",
    phoneNumber: "001-384-340-8583",
    email: "yblake@example.net",
    outstandingAmount: 9380,
  },
  {
    name: "Elizabeth Oliver",
    address: "Ontario Manitoba",
    phoneNumber: "(059)448-1986x875",
    email: "jackiekeller@example.net",
    outstandingAmount: 4456,
  },
  {
    name: "Tyler Castaneda",
    address: "Northern Ireland South Carolina",
    phoneNumber: "459.247.9935x191",
    email: "ashley31@example.net",
    outstandingAmount: 9563,
  },
  {
    name: "Edward Gibson",
    address: "Wisconsin England",
    phoneNumber: "310-473-5990",
    email: "ajordan@example.com",
    outstandingAmount: 26851,
  },
  {
    name: "Penny Perez",
    address: "Wisconsin South Carolina",
    phoneNumber: "711-094-4691x790",
    email: "ashleydaniel@example.net",
    outstandingAmount: 276,
  },
  {
    name: "Erin Johnston",
    address: "British Columbia Indiana",
    phoneNumber: "500.457.0808x251",
    email: "adamsjennifer@example.org",
    outstandingAmount: 330,
  },
  {
    name: "Valerie Morales",
    address: "Quebec New Hampshire",
    phoneNumber: "4370806265",
    email: "andrew05@example.net",
    outstandingAmount: 181,
  },
  {
    name: "Hannah Lee",
    address: "New York Georgia",
    phoneNumber: "001-734-633-1409x31832",
    email: "katherine57@example.org",
    outstandingAmount: 265,
  },
  {
    name: "Tina Chandler",
    address: "Nova Scotia Pennsylvania",
    phoneNumber: "(860)996-9037x8493",
    email: "pramirez@example.com",
    outstandingAmount: 8999,
  },
  {
    name: "Timothy Huerta",
    address: "Indiana Arizona",
    phoneNumber: "+1-874-945-6161x35147",
    email: "jensendonna@example.org",
    outstandingAmount: 3901,
  },
  {
    name: "Jonathan Young",
    address: "Alberta Nebraska",
    phoneNumber: "736.747.2563",
    email: "sydneymorris@example.net",
    outstandingAmount: 319,
  },
  {
    name: "Chelsea Shields",
    address: "Northern Ireland Massachusetts",
    phoneNumber: "+1-866-752-6542",
    email: "ewarner@example.com",
    outstandingAmount: 4610,
  },
  {
    name: "Eric Espinoza",
    address: "Rhode Island Texas",
    phoneNumber: "(424)009-3704x7412",
    email: "cheryl36@example.com",
    outstandingAmount: 477,
  },
  {
    name: "Christopher Romero",
    address: "Northwest Territories New Mexico",
    phoneNumber: "629.244.9777x1155",
    email: "amyhenderson@example.com",
    outstandingAmount: 69445,
  },
  {
    name: "Christopher Vargas",
    address: "Texas Montana",
    phoneNumber: "+1-983-865-0674",
    email: "tcarlson@example.net",
    outstandingAmount: 5093,
  },
  {
    name: "Andrew Edwards",
    address: "Delaware Connecticut",
    phoneNumber: "+1-187-623-3205x86407",
    email: "zhall@example.com",
    outstandingAmount: 41321,
  },
  {
    name: "Tina Peterson",
    address: "New Hampshire Alaska",
    phoneNumber: "+1-258-078-9524x280",
    email: "sandersjustin@example.com",
    outstandingAmount: 619,
  },
  {
    name: "Joseph Herrera",
    address: "England Idaho",
    phoneNumber: "(912)942-7086x643",
    email: "qcompton@example.org",
    outstandingAmount: 6886,
  },
  {
    name: "Nancy Summers",
    address: "Wyoming Wyoming",
    phoneNumber: "(348)442-9294x8002",
    email: "hestrada@example.net",
    outstandingAmount: 3864,
  },
  {
    name: "Karen Padilla",
    address: "West Virginia Colorado",
    phoneNumber: "(655)465-0155",
    email: "forbesandrea@example.com",
    outstandingAmount: 7210,
  },
  {
    name: "John Diaz",
    address: "Massachusetts Missouri",
    phoneNumber: "001-645-736-3951",
    email: "gregoryanthony@example.com",
    outstandingAmount: 44719,
  },
  {
    name: "Todd Luna",
    address: "Quebec Indiana",
    phoneNumber: "663.328.0566x191",
    email: "doyletonya@example.net",
    outstandingAmount: 97225,
  },
  {
    name: "Nancy Adams",
    address: "Pennsylvania Vermont",
    phoneNumber: "001-077-970-8408x59346",
    email: "johnstonryan@example.com",
    outstandingAmount: 2840,
  },
  {
    name: "Dustin Carpenter",
    address: "Connecticut Louisiana",
    phoneNumber: "209-484-3414x764",
    email: "jessica36@example.net",
    outstandingAmount: 239,
  },
  {
    name: "Jennifer Cook",
    address: "Delaware Northwest Territories",
    phoneNumber: "052-243-1895x929",
    email: "tammy09@example.com",
    outstandingAmount: 675,
  },
  {
    name: "Zachary George",
    address: "Manitoba Maryland",
    phoneNumber: "(916)912-7750",
    email: "campbelleric@example.org",
    outstandingAmount: 450,
  },
  {
    name: "Melanie Todd",
    address: "Oregon Kentucky",
    phoneNumber: "(681)558-9545",
    email: "mary70@example.net",
    outstandingAmount: 2603,
  },
  {
    name: "Joseph Allen",
    address: "Connecticut District of Columbia",
    phoneNumber: "+1-856-903-9481x4787",
    email: "qgray@example.net",
    outstandingAmount: 7864,
  },
  {
    name: "Keith Anderson",
    address: "New Hampshire New Mexico",
    phoneNumber: "306-681-7331x44949",
    email: "danielle97@example.net",
    outstandingAmount: 29410,
  },
  {
    name: "Alan Russo",
    address: "England Iowa",
    phoneNumber: "118-432-9010",
    email: "loganherrera@example.net",
    outstandingAmount: 8850,
  },
  {
    name: "Lawrence Richardson",
    address: "West Virginia Ontario",
    phoneNumber: "285-795-3720x803",
    email: "justin49@example.net",
    outstandingAmount: 654,
  },
  {
    name: "Valerie Thomas",
    address: "Washington Maryland",
    phoneNumber: "0388601472",
    email: "tallen@example.com",
    outstandingAmount: 933,
  },
  {
    name: "Molly Smith",
    address: "Alaska New York",
    phoneNumber: "923.620.9641",
    email: "ygomez@example.net",
    outstandingAmount: 928,
  },
  {
    name: "Megan Lane",
    address: "Connecticut Minnesota",
    phoneNumber: "169-361-6279x05649",
    email: "sarasolis@example.com",
    outstandingAmount: 71329,
  },
  {
    name: "Nathan Brown",
    address: "Pennsylvania Wyoming",
    phoneNumber: "183.271.8222x2177",
    email: "ovargas@example.org",
    outstandingAmount: 4018,
  },
  {
    name: "Richard Rivera",
    address: "Northern Ireland Nebraska",
    phoneNumber: "001-041-679-4633",
    email: "daniel29@example.com",
    outstandingAmount: 6930,
  },
  {
    name: "Katherine Mcbride",
    address: "Hawaii New Jersey",
    phoneNumber: "001-727-218-6650",
    email: "coffeyjeffrey@example.com",
    outstandingAmount: 1126,
  },
  {
    name: "Emily Parker",
    address: "Iowa Rhode Island",
    phoneNumber: "(116)376-1994x9505",
    email: "angeladavis@example.com",
    outstandingAmount: 124,
  },
  {
    name: "Samuel Vargas",
    address: "Michigan South Dakota",
    phoneNumber: "+1-911-983-5460x9009",
    email: "leahgonzalez@example.com",
    outstandingAmount: 810,
  },
  {
    name: "Emily Moore",
    address: "Alaska Wyoming",
    phoneNumber: "340-199-9161",
    email: "timothy51@example.net",
    outstandingAmount: 503,
  },
  {
    name: "Mary Gonzalez",
    address: "Oklahoma Manitoba",
    phoneNumber: "226.131.5042x99663",
    email: "mackenziehall@example.org",
    outstandingAmount: 176,
  },
  {
    name: "Brooke Morales",
    address: "Connecticut Alberta",
    phoneNumber: "(009)805-5829x9095",
    email: "bryanelliott@example.org",
    outstandingAmount: 1437,
  },
  {
    name: "James Alvarado",
    address: "Louisiana Nova Scotia",
    phoneNumber: "001-140-651-1632x683",
    email: "janderson@example.org",
    outstandingAmount: 31005,
  },
  {
    name: "Tasha Smith",
    address: "New Mexico Oregon",
    phoneNumber: "(042)505-2472",
    email: "amberjohnson@example.com",
    outstandingAmount: 463,
  },
  {
    name: "Kristin Orr",
    address: "Colorado Northwest Territories",
    phoneNumber: "112.936.6186x451",
    email: "timothy91@example.com",
    outstandingAmount: 71794,
  },
  {
    name: "Megan Shaw",
    address: "Mississippi British Columbia",
    phoneNumber: "129.877.6596",
    email: "yfoster@example.net",
    outstandingAmount: 698,
  },
  {
    name: "Jacob Elliott",
    address: "Washington Iowa",
    phoneNumber: "(862)908-2526",
    email: "agordon@example.org",
    outstandingAmount: 14116,
  },
  {
    name: "Amanda Thompson",
    address: "Yukon Northwest Territories",
    phoneNumber: "627.283.2969x74124",
    email: "calhounapril@example.com",
    outstandingAmount: 606,
  },
  {
    name: "Jonathan Mayer",
    address: "Alabama Alabama",
    phoneNumber: "001-234-805-2296",
    email: "hgriffith@example.net",
    outstandingAmount: 45360,
  },
  {
    name: "Brandon Haley",
    address: "Quebec Wales",
    phoneNumber: "+1-708-267-9160x22748",
    email: "rogerbrown@example.org",
    outstandingAmount: 60873,
  },
  {
    name: "Maria Shields",
    address: "Michigan Northwest Territories",
    phoneNumber: "001-936-472-7261x80651",
    email: "craig68@example.net",
    outstandingAmount: 740,
  },
  {
    name: "Eduardo Curtis",
    address: "Maryland Delaware",
    phoneNumber: "789-004-3218",
    email: "lisa20@example.net",
    outstandingAmount: 953,
  },
  {
    name: "Tamara Campbell",
    address: "Northwest Territories Minnesota",
    phoneNumber: "539.612.1047x65113",
    email: "thompsonmadeline@example.org",
    outstandingAmount: 1974,
  },
  {
    name: "Maria Brown",
    address: "Manitoba Hawaii",
    phoneNumber: "613-459-3478",
    email: "nsantos@example.net",
    outstandingAmount: 7910,
  },
  {
    name: "Holly Martinez",
    address: "Louisiana Indiana",
    phoneNumber: "001-120-412-8725x93714",
    email: "keith51@example.com",
    outstandingAmount: 80164,
  },
  {
    name: "Sherry Vaughn",
    address: "Maryland Michigan",
    phoneNumber: "721.938.0647x079",
    email: "lindsay88@example.com",
    outstandingAmount: 55426,
  },
  {
    name: "Justin Lane",
    address: "Pennsylvania Newfoundland and Labrador",
    phoneNumber: "001-624-264-1814x93322",
    email: "martintammy@example.com",
    outstandingAmount: 644,
  },
  {
    name: "Charles Schultz",
    address: "Iowa Northwest Territories",
    phoneNumber: "001-277-115-0867x7228",
    email: "robbinsjordan@example.net",
    outstandingAmount: 87316,
  },
  {
    name: "Janet Li",
    address: "Massachusetts Ontario",
    phoneNumber: "5923788399",
    email: "hollowayjohn@example.org",
    outstandingAmount: 608,
  },
  {
    name: "Tyler Wagner",
    address: "South Carolina Indiana",
    phoneNumber: "001-266-219-5727x02134",
    email: "julie79@example.net",
    outstandingAmount: 17168,
  },
  {
    name: "Christine Perry",
    address: "Illinois Saskatchewan",
    phoneNumber: "001-555-042-4746x4106",
    email: "debra53@example.com",
    outstandingAmount: 81861,
  },
  {
    name: "Cindy Conrad",
    address: "California California",
    phoneNumber: "(121)390-9226x65969",
    email: "lewisrobin@example.com",
    outstandingAmount: 74040,
  },
  {
    name: "Lisa Morris",
    address: "Illinois Prince Edward Island",
    phoneNumber: "373-934-3549",
    email: "markpadilla@example.com",
    outstandingAmount: 9555,
  },
  {
    name: "David Taylor",
    address: "North Dakota Maryland",
    phoneNumber: "001-335-354-8195x62006",
    email: "william31@example.org",
    outstandingAmount: 7267,
  },
  {
    name: "Laura Pope",
    address: "Florida Quebec",
    phoneNumber: "291-786-6136x14883",
    email: "usanders@example.com",
    outstandingAmount: 9721,
  },
  {
    name: "Dustin Washington",
    address: "North Carolina Kentucky",
    phoneNumber: "389-237-4727",
    email: "russell53@example.com",
    outstandingAmount: 129,
  },
  {
    name: "Lisa Watkins",
    address: "Manitoba Massachusetts",
    phoneNumber: "(793)066-4588x9238",
    email: "millerandrew@example.com",
    outstandingAmount: 432,
  },
  {
    name: "Mia Sullivan",
    address: "Maryland Florida",
    phoneNumber: "+1-065-616-2867x85673",
    email: "youngandrew@example.net",
    outstandingAmount: 325,
  },
  {
    name: "Diana Burns",
    address: "Montana Nebraska",
    phoneNumber: "(910)858-6646",
    email: "carla71@example.com",
    outstandingAmount: 6151,
  },
  {
    name: "Arthur Sanchez",
    address: "Montana Utah",
    phoneNumber: "001-148-760-5147",
    email: "elizabethmendoza@example.org",
    outstandingAmount: 164,
  },
  {
    name: "Sabrina Jordan",
    address: "Alabama Arkansas",
    phoneNumber: "339-085-7509x3595",
    email: "matthewconley@example.com",
    outstandingAmount: 54408,
  },
  {
    name: "Nathan Ryan",
    address: "Scotland Wyoming",
    phoneNumber: "(935)219-7346x993",
    email: "anthony34@example.net",
    outstandingAmount: 2224,
  },
  {
    name: "Kristen Wells",
    address: "Massachusetts Maine",
    phoneNumber: "001-850-650-2022x44676",
    email: "mark51@example.net",
    outstandingAmount: 7002,
  },
  {
    name: "Shannon Ford",
    address: "Montana Vermont",
    phoneNumber: "001-891-353-9515x29826",
    email: "urodriguez@example.net",
    outstandingAmount: 1755,
  },
  {
    name: "Grace Evans",
    address: "West Virginia North Carolina",
    phoneNumber: "+1-463-570-8565x6692",
    email: "jeff01@example.com",
    outstandingAmount: 9739,
  },
  // {
  //   name: "Connor Wise",
  //   address: "North Carolina South Carolina",
  //   phoneNumber: "+1-878-571-3875x4486",
  //   email: "wbrowning@example.com",
  //   outstandingAmount: 18492,
  // },
  // {
  //   name: "Ellen Diaz",
  //   address: "Connecticut Virginia",
  //   phoneNumber: "+1-890-572-7164x8819",
  //   email: "jonesangela@example.com",
  //   outstandingAmount: 5983,
  // },
  // {
  //   name: "Raymond Perez",
  //   address: "Scotland Massachusetts",
  //   phoneNumber: "085.775.0003x28311",
  //   email: "scott31@example.com",
  //   outstandingAmount: 70751,
  // },
  // {
  //   name: "Penny Pena",
  //   address: "Iowa New Mexico",
  //   phoneNumber: "+1-422-769-8322",
  //   email: "earl58@example.net",
  //   outstandingAmount: 98691,
  // },
  // {
  //   name: "James Dillon",
  //   address: "Michigan Georgia",
  //   phoneNumber: "506-421-3830",
  //   email: "lschultz@example.org",
  //   outstandingAmount: 59607,
  // },
  // {
  //   name: "Jennifer Harrison",
  //   address: "England Quebec",
  //   phoneNumber: "001-987-872-2804x5792",
  //   email: "delacruztravis@example.org",
  //   outstandingAmount: 8531,
  // },
  // {
  //   name: "Christopher Duncan",
  //   address: "Kansas Alaska",
  //   phoneNumber: "(942)058-6971x4779",
  //   email: "martinezanna@example.net",
  //   outstandingAmount: 9092,
  // },
  // {
  //   name: "Richard Hodge",
  //   address: "Wyoming Prince Edward Island",
  //   phoneNumber: "732.256.4556",
  //   email: "mary27@example.org",
  //   outstandingAmount: 40937,
  // },
  // {
  //   name: "Tracey Wade",
  //   address: "Vermont Wisconsin",
  //   phoneNumber: "937-986-2768",
  //   email: "sholt@example.com",
  //   outstandingAmount: 33678,
  // },
  // {
  //   name: "Stacy Weaver",
  //   address: "Georgia Wisconsin",
  //   phoneNumber: "996-574-7991x14532",
  //   email: "woodsmartha@example.net",
  //   outstandingAmount: 19439,
  // },
  // {
  //   name: "Evan Mathews",
  //   address: "North Dakota Mississippi",
  //   phoneNumber: "2056742342",
  //   email: "jamesparker@example.org",
  //   outstandingAmount: 684,
  // },
  // {
  //   name: "Amy Brown",
  //   address: "Idaho Oregon",
  //   phoneNumber: "979.299.5663x41550",
  //   email: "loriprice@example.org",
  //   outstandingAmount: 52312,
  // },
  // {
  //   name: "Robert Owens",
  //   address: "Oklahoma New York",
  //   phoneNumber: "959-488-5833",
  //   email: "michellejones@example.org",
  //   outstandingAmount: 7595,
  // },
];
